ALTER TABLE Measures DROP CONSTRAINT FK_DimensionX;
ALTER TABLE Measures DROP CONSTRAINT FK_DimensionY;
ALTER TABLE Measures DROP CONSTRAINT FK_User;

DROP TABLE Measures;
DROP TABLE Dimensions;
DROP TABLE Scenarios;
DROP TABLE Users;